### ISSUE TITLE
Error in rule buildGraph:

### ISSUE THREAD

**Issue by sigau** [marbl/verkko#131]
Hello. Thanks so much for providing this resource to the community! 
I instal verkko using conda.
I was trying to co-assemble hifi and ont data using verkko and encounter the following error :

"
Error in rule buildGraph:
    jobid: 4
    input: hifi-corrected.fasta.gz
    output: 1-buildGraph/hifi-resolved.gfa, 1-buildGraph/hifi_nodecov.csv, 1-buildGraph/paths.gaf
    log: 1-buildGraph/buildGraph.err (check log file(s) for error details)
    shell:
"
And when I look at the log file I have this : 

MBG: src/HPCConsensus.cpp:145: std::vector<std::tuple<long unsigned int, long unsigned int, long unsigned int, long unsigned int, bool, long unsigned int, long unsigned int> > getMatchBlocks(const std::vector<std::vector<long unsigned int> >&, const UnitigGraph&, const ReadPath&, std::vector<long unsigned int>, size_t, size_t): Assertion `readEnd - readStart == unitigEnd - unitigStart' failed.
Aborted

I saw in the issue #67 that it could be the version of MBG (1.0.10) but mine is  more recent (1.0.14).

[buildGraph.err.txt](https://github.com/marbl/verkko/files/10989460/buildGraph.err.txt)
[verkko_assembly.e.txt](https://github.com/marbl/verkko/files/10989461/verkko_assembly.e.txt)
[verkko_assembly.out.txt](https://github.com/marbl/verkko/files/10989462/verkko_assembly.out.txt)

**Comment by sigau** [comment]
Sure : 
https://filesender.renater.fr/?s=download&token=ace316b8-865c-43b0-b542-e5f0c7f1b905

**Comment by maickrau** [comment]
Newest MBG commit [20d493d](https://github.com/maickrau/MBG/commit/20d493dcac1f812428b0efab4914b44dbea2629a) should now fix this.

**Comment by sigau** [comment]
Hi,
I retry to run verkko with the last commit of MBG but still get the same error with the rule buildGraph

**Comment by maickrau** [comment]
That's strange, my manual run worked. Could you check that `1-buildGraph/buildGraph.err` has this version info somewhere near the start: `MBG Branch master commit 20d493dcac1f812428b0efab4914b44dbea2629a`

**Comment by sigau** [comment]
[buildGraph.err.txt](https://github.com/marbl/verkko/files/11049450/buildGraph.err.txt)
it seems to be the right release

**Comment by maickrau** [comment]
Yes, it's the right version. Looks like this hit some nondeterminism bug in MBG. The error is same as MBG issue 19 https://github.com/maickrau/MBG/issues/19 but your run and my run have slightly different results based on logs, and this difference was enough to cause a crash.

**Comment by sigau** [comment]
Ok so should wait for the next update of MBG ?

**Comment by maickrau** [comment]
You can try rerunning and hope that the nondeterminism just happens to not crash, or wait for an update.

**Comment by maickrau** [comment]
Now you can try rerunning with the latest MBG version which fixed the error in the other issue. My rerun did not run into this issue due to nondeterminism so I couldn't verify if it fixed this issue, but if it was caused by the same bug then it should run.

**Comment by sigau** [comment]
Hi !
Effectively this resolve my problem with this error for the rule buildGraph but got an new error with the rule processONT now should I open a new issue ?

**Comment by skoren** [comment]
Yes, open a new issue for that.
